### ISSUE TITLE
debug version of  static ffmpeg

### ISSUE THREAD

**Issue by Akagi201** [pyke369/sffmpeg#13]
Firstly, nice job!

I want to debug ffmpeg using gdb, you know that a static binary will make it easy.

So Where can I add the ffmpeg configure options(--enable-debug)

**Comment by pyke369** [comment]
Hello,

Just add it to the CONFIGURE_COMMAND line in the EXTERNALPROJECT_ADD(ffmpeg) section of the CMakeLists.txt file.

Cheers,
Pierre-Yves
