### ISSUE TITLE
Is it possible to use this script to compile ffmpeg from latest git repo?

### ISSUE THREAD

**Issue by zenny** [pyke369/sffmpeg#17]
It would be nice if this script can by tweaked to compile ffmpeg from the latest git repo.

**Comment by pyke369** [comment]
Hi Zenny,

it's relatively easy to do. In the CMakeLists.txt file, just replace the URL directive around line #180 by a GIT_REPOSITORY directive. For instance:
``` 
URL http://www.ffmpeg.org/releases/ffmpeg-2.8.1.tar.bz2
```
would be replaced by:
```
GIT_REPOSITORY  git://source.ffmpeg.org/ffmpeg.git
```
Pierre-Yves
